---

- name: minikube | create local temporary directory
  tempfile:
    state: directory
    suffix: binary
  changed_when: false
  delegate_to: 127.0.0.1
  register: minikubeDownloadDirectory

- name: download sha256sum
  get_url:
    url: '{{ minikube_mirror }}/{{ minikube_redis_filename }}.sha256'
    dest: '{{ minikubeDownloadDirectory.path }}/{{ minikube_download_filename }}.sha256'
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'
  delegate_to: 127.0.0.1

- name: read sha256sum
  slurp:
    src: '{{ minikubeDownloadDirectory.path }}/{{ minikube_download_filename }}.sha256'
  register: minikube_sha256sum
  delegate_to: 127.0.0.1

- name: download Minikube
  get_url:
    url: '{{ minikube_mirror }}/{{ minikube_redis_filename }}'
    dest: '{{ minikubeDownloadDirectory.path }}/{{ minikube_download_filename }}'
    sha256sum: '{{ minikube_sha256sum.content | b64decode | trim }}'
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'
  delegate_to: 127.0.0.1

- name: create the Minikube installation dir
  become: yes
  file:
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    dest: '{{ minikube_install_dir }}'

- name: install Minikube
  become: yes
  copy:
    src: '{{ minikubeDownloadDirectory.path }}/{{ minikube_download_filename }}'
    dest: '{{ minikube_install_path }}'
    force: yes
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
